import Head from 'next/head'
import UserList from '../components/UserList'

export default function Home() {
  return (
    <div>
      <Head>
        <title>ATG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <UserList/>
      

    </div>
  )
}
